# 大功能：让不同形状的数组能一起运算。
你以后会遇到：
每个序列的 embedding 减去全体均值；
每个序列的计数除以该序列总长度；
相似度矩阵乘一个权重向量；
一个 (100, 128) 的矩阵，减去 (128,) 的均值向量。
这些都靠广播。
# 小颗粒与标记
数组与标量运算	          【必须会】
同形状数组运算	          【必须会】
广播规则：从右往左对齐	  【必须会】
维度相等或其中一个为 1	  【必须会】
keepdims=True	          【必须会】
按行归一化、按列中心化	  【必须会】
np.newaxis 增加维度	      【知道即可】
broadcast_to	          【知道即可】
广播性能、stride	          【暂不学】
# 广播的三条规则
维度相等：比如都是 3。
如：（4,3）对（4,3）→（4,3）
其中一个是 1：比如 3 和 1，可以扩展成 3。
如：（4,1）对（1,3）→ （4,3）
其中一方缺失：缺失的那一方会被当成 1，然后按第 2 条扩展。
（4,3）对（  3，）→   （4,3）
A:  2  3  4
B:     3  1
# 小tips
1. numpy中的sum用法：参考mean，mean是求平均值，但是sum就是求那一维的和。
keepdims参数：是否保持维度。（用shape看一看）
2. 改一改sum中的axis和keepdimds，看看归一化操作还能行吗
3. 中心化一般叫对axis=k做中心化。
操作：
1.mean求axis=k的均值，注意keepdims
2.原矩阵-均值，得到的就是已经中心化的矩阵
# 功能大全
## 广播：
让不同形状数组能直接运算。
写代码更短，运行更快。
## 中心化：
去掉均值偏移。
PCA、协方差、线性回归等预处理常用。
## 归一化 / 标准化：
统一特征尺度。
防止大数值特征主导。
加速训练，提高模型效果。
## 
中心化是标准化的一部分。
标准化 = 中心化 + 缩放。
归一化这个词要看上下文，可能是 Min-Max，也可能是标准化。

In [1]:
import numpy as np 
import random

In [2]:
counts = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

In [19]:
#以下是归一化操作（把某一维的和变成1）
row_sum = counts.sum(axis=1, keepdims=True)
print(row_sum)

[[ 6]
 [15]]


In [20]:
norm = counts / row_sum
print(norm)
print(norm.shape)
print(norm.sum(axis=1))
#归一化操作结束

[[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]
(2, 3)
[1. 1.]


In [22]:
#每列中心化
col_mean = counts.mean(axis=0)
centered = counts  -col_mean
print(centered)
print(centered.mean(axis=0))

[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
[0. 0. 0.]


In [26]:
import numpy as np

X = np.array([[1, 100],
              [2, 200],
              [3, 300]])

# 中心化
X_centered = X - X.mean(axis=0)

# 标准化
X_standard = (X - X.mean(axis=0)) / X.std(axis=0)

# Min-Max 归一化
X_minmax = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

print("中心化:\n", X_centered)
print("标准化:\n", X_standard)
print("Min-Max 归一化:\n", X_minmax)

中心化:
 [[  -1. -100.]
 [   0.    0.]
 [   1.  100.]]
标准化:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
Min-Max 归一化:
 [[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [33]:
# 广播
import numpy as np

a = np.array([[1],
              [2],
              [3]])        # 形状 (3, 1)

b = np.array([10, 20, 30, 40])  # 形状 (4,)

c = a + b
print(c)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [34]:
rng =np.random.default_rng(42)
a = rng.integers(1,10,(4,3))
print(a)

[[1 7 6]
 [4 4 8]
 [1 7 2]
 [1 5 9]]


In [38]:
row_sum = a.sum(axis=1,keepdims=True)
print(row_sum)

[[14]
 [16]
 [10]
 [15]]


In [47]:
norm =a/ row_sum
print(norm)

[[0.07142857 0.5        0.42857143]
 [0.25       0.25       0.5       ]
 [0.1        0.7        0.2       ]
 [0.06666667 0.33333333 0.6       ]]


In [62]:
col_mean = a.mean(axis=0,keepdims=True)
print(col_mean)
centered = a - col_mean
#print(centered)
print(centered.mean(axis=0))

[[1.75 5.75 6.25]]
[0. 0. 0.]
