# 大功能：从一堆数里算出概括信息，并找出最大/最小的那些。
你以后会遇到：
一批 RNA 序列的长度均值、最大值、标准差；
一次搜索返回 10000 个得分，取 top-10；
相似度矩阵每行取最大，看每条序列最像谁；
按得分排序，看命中分布。
# 小颗粒与标记
sum/mean/std/min/max	    【必须会】
argmin/argmax	            【必须会】
sort 与 argsort         	【必须会】
取 top-k                	【必须会】
axis 配合聚合	            【必须会】
percentile/median	        【必须会】
unique 与计数	            【知道即可】
nan 处理                	【知道即可】
bincount/histogram      	【暂不学】
# tips
1. 基础聚合
a = np.array([50, 120, 80, 200, 30])
a.sum()      # 480
a.mean()     # 96.0
a.std()      # 标准差
a.min()      # 30
a.max()      # 200
a.argmin()   # 4，最小值在索引4
a.argmax()   # 3，最大值在索引3
2. 排序：
scores = np.array([0.5, 0.9, 0.1, 0.7])
np.sort(scores)              # [0.1 0.5 0.7 0.9]，返回新数组
np.argsort(scores)           # [2 0 3 1]，返回排序后的原索引
scores[np.argsort(scores)]   # 等价于 np.sort(scores)
order = np.argsort(scores)[::-1]   # [1 3 0 2]
scores[order]                      # [0.9 0.7 0.5 0.1]
3. top-k：
k = 2
top_idx = np.argsort(scores)[::-1][:k]   # 前2大的索引
top_val = scores[top_idx]
print(top_idx, top_val)                   # [1 3] [0.9 0.7]
4. 配合 axis：
m = np.array([
    [1, 9, 3],
    [4, 2, 8],
])
m.max(axis=1)      # [9 8]，每行最大值
m.argmax(axis=1)   # [1 2]，每行最大值所在的列索引
5.  中位数和百分位：
a = np.array([10, 20, 30, 40, 100])
np.median(a)            # 30
np.percentile(a, 90)    # 90分位数
6. max(axis=1),意味着只在axis=1这一维中取最大值
如：（4,5,2）→（4,2），矩阵中每一个最值都是对应axis=1中的最值

In [12]:
import numpy as np

In [11]:
a = np.array([45, 120, 78, 210, 33, 160, 95])
b = np.argsort(a)[0:3]
print(b)
print(a[b])

[4 0 2]
[33 45 78]


In [23]:
rng=np.random.default_rng(42)
c = rng.integers(0,100,(4,5,2))
print(c)

[[[ 8 77]
  [65 43]
  [43 85]
  [ 8 69]
  [20  9]]

 [[52 97]
  [73 76]
  [71 78]
  [51 12]
  [83 45]]

 [[50 37]
  [18 92]
  [78 64]
  [40 82]
  [54 44]]

 [[45 22]
  [ 9 55]
  [88  6]
  [85 82]
  [27 63]]]


In [25]:
d = c.max(axis=1)
e = c.argmax(axis=1)
print(d.shape)
print(e)

(4, 2)
[[1 2]
 [4 0]
 [2 1]
 [2 3]]


In [29]:
f =np.median(c)
print(f)
g = np.percentile(c,90,axis=1)
print(g)

53.0
[[56.2 81.8]
 [79.  89.4]
 [68.4 88. ]
 [86.8 74.4]]
