# 大功能：从数组里精确取出你要的部分。
你以后处理 RNA 数据会遇到：
取第 5 条序列的长度 → 单个索引
取前 10 条序列 → 切片
取出所有长度大于 100 的序列 → 布尔筛选
取出所有序列的前 4 列碱基计数 → 二维切片
把长度小于 50 的序列去掉 → 布尔筛选 + 赋值
这一课的核心就一句话：先定位，再取值。
#  小颗粒与标记
一维索引 a[0]、a[-1]	                【必须会】
一维切片 a[1:4]、a[:3]、a[::2]	    【必须会】
二维索引 b[0, 1]、b[0]、b[:, 1]	    【必须会】
二维切片 b[0:2, 1:3]	                【必须会】
布尔掩码 a[a > 50]	                【必须会】
布尔掩码组合 &、|、~	                【必须会】
np.where	                        【知道即可】
花式索引 a[[0, 2, 4]]	            【知道即可】
视图 vs 拷贝	                        【暂不学】

# random 的使用
## 设置随机数种子
rng = np.random.default_rng(42)
## 根据随机数种子使用分布
旧写法（np.random.xxx）	        新写法（rng.xxx）
np.random.rand(2, 3)	        rng.random((2, 3))            #[0,1)均匀分布
np.random.randn(2, 3)	        rng.standard_normal((2, 3))   #标准正态分布
np.random.randint(1, 7, 10)	    rng.integers(1, 7, 10)        #[1,7)整数
np.random.normal(0, 1, 5)	    rng.normal(0, 1, 5)           #正态分布
np.random.uniform(0, 1, 5)	    rng.uniform(0, 1, 5)          #均匀分布
np.random.choice([1,2,3], 5)	rng.choice([1,2,3], 5)        #随机选择
np.random.shuffle(x)	        rng.shuffle(x)                #原地打乱

# 小tip
1. 矩阵中直接独有的：如矩阵[1,2,3]>1返回的是矩阵[False,Ture,Ture]
2. a[0]和a[0,2],一个用了一维的索引，一个用了二维的；对于[4,3]矩阵，0先找4那一维的，2找3那一维的，从左向右
3. 像normal这样的，最后一个参数决定了生成多少个，5→5个+一维；（4,3）→4x3+二维。不过这里尽量传元组

# 及其重要的题目
用布尔筛选，从 counts 中取出第 1 列大于某阈值的那些行。
看下面

In [11]:
import numpy as np
import random


In [9]:

lengths  = np.array([45, 120, 78, 210, 33, 160, 95])

print(lengths[0],lengths[-1],lengths[2:5])


45 95 [ 78 210  33]


In [10]:

mark = lengths >100
print(lengths[mark])


[120 210 160]


In [13]:
mark1 = (50<=lengths) & (lengths<=150)
print(lengths[mark1])

[120  78  95]


In [57]:
rng = np.random.default_rng(42)
a =rng.uniform(1, 7,(4,3,2))
print(a[0],"\n",a[:,-1],"\n",a[1:3,0:2])

[[5.64373629 3.63327064]
 [6.15158752 5.18420817]
 [1.56506409 6.85373411]] 
 [[1.56506409 6.85373411]
 [3.22478815 6.56058993]
 [4.32750872 1.38290354]
 [6.82418815 6.35872673]] 
 [[[5.56683821 5.71638583]
  [1.7686818  3.70231563]]

 [[4.86319072 5.93656968]
  [3.66048519 2.36343233]]]


In [72]:
# 用布尔筛选，从 counts 中取出第 1 列大于某阈值的那些行。
mark1 = a[:,:,0] >0
print(mark1.shape)
print(a.shape)
print(a[mark1].shape)
print(np.array_equal(a,a[mark1].reshape(4,3,2)))

(4, 3)
(4, 3, 2)
(12, 2)
True


对于mark1(4,3),他是这么找的
4x3=12
4与4对齐，往下比对，这个Ture，留下...
一行比对完了，下一行，最后留下12个，（12,2）中的12就是这么来的
而其中的二更像是“基本单元”那样的
如：（4,3）对（4,3,2），2那一维就是基本单元
（4，）对（4,3,2），（3,2）这一个二维空间就是基本单元
# 布尔索引的建立
1. 要考虑基本单元的选取
2. 索引要跟对齐（可部分）